//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pickbyopen.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class SCodeBarsReader : global::System.Configuration.ApplicationSettingsBase {
        
        private static SCodeBarsReader defaultInstance = ((SCodeBarsReader)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SCodeBarsReader())));
        
        public static SCodeBarsReader Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string COM {
            get {
                return ((string)(this["COM"]));
            }
            set {
                this["COM"] = value;
            }
        }
    }
}
