//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pickbyopen.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class SPlcAddresses : global::System.Configuration.ApplicationSettingsBase {
        
        private static SPlcAddresses defaultInstance = ((SPlcAddresses)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SPlcAddresses())));
        
        public static SPlcAddresses Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.0")]
        public string ReadIsOpen1 {
            get {
                return ((string)(this["ReadIsOpen1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.1")]
        public string ReadIsOpen2 {
            get {
                return ((string)(this["ReadIsOpen2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.2")]
        public string ReadIsOpen3 {
            get {
                return ((string)(this["ReadIsOpen3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.3")]
        public string ReadIsOpen4 {
            get {
                return ((string)(this["ReadIsOpen4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.4")]
        public string ReadIsOpen5 {
            get {
                return ((string)(this["ReadIsOpen5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.5")]
        public string ReadIsOpen6 {
            get {
                return ((string)(this["ReadIsOpen6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.6")]
        public string ReadIsOpen7 {
            get {
                return ((string)(this["ReadIsOpen7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX2.7")]
        public string ReadIsOpen8 {
            get {
                return ((string)(this["ReadIsOpen8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX3.0")]
        public string ReadIsOpen9 {
            get {
                return ((string)(this["ReadIsOpen9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX3.1")]
        public string ReadIsOpen10 {
            get {
                return ((string)(this["ReadIsOpen10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX3.2")]
        public string ReadIsOpen11 {
            get {
                return ((string)(this["ReadIsOpen11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX3.3")]
        public string ReadIsOpen12 {
            get {
                return ((string)(this["ReadIsOpen12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX3.4")]
        public string ReadIsOpen13 {
            get {
                return ((string)(this["ReadIsOpen13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX3.5")]
        public string ReadIsOpen14 {
            get {
                return ((string)(this["ReadIsOpen14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX3.6")]
        public string ReadIsOpen15 {
            get {
                return ((string)(this["ReadIsOpen15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX3.7")]
        public string ReadIsOpen16 {
            get {
                return ((string)(this["ReadIsOpen16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX4.0")]
        public string ReadIsOpen17 {
            get {
                return ((string)(this["ReadIsOpen17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX4.1")]
        public string ReadIsOpen18 {
            get {
                return ((string)(this["ReadIsOpen18"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX4.2")]
        public string ReadNeedsRefill10 {
            get {
                return ((string)(this["ReadNeedsRefill10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX4.3")]
        public string ReadNeedsRefill11 {
            get {
                return ((string)(this["ReadNeedsRefill11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX4.4")]
        public string ReadNeedsRefill12 {
            get {
                return ((string)(this["ReadNeedsRefill12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX4.5")]
        public string ReadNeedsRefill13 {
            get {
                return ((string)(this["ReadNeedsRefill13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX4.6")]
        public string ReadNeedsRefill14 {
            get {
                return ((string)(this["ReadNeedsRefill14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX4.7")]
        public string ReadNeedsRefill15 {
            get {
                return ((string)(this["ReadNeedsRefill15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX5.0")]
        public string ReadNeedsRefill16 {
            get {
                return ((string)(this["ReadNeedsRefill16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX5.1")]
        public string ReadNeedsRefill17 {
            get {
                return ((string)(this["ReadNeedsRefill17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX5.2")]
        public string ReadNeedsRefill18 {
            get {
                return ((string)(this["ReadNeedsRefill18"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX5.3")]
        public string ReadPlcStatus {
            get {
                return ((string)(this["ReadPlcStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.DBX5.4")]
        public string ReadDoorIsOpen {
            get {
                return ((string)(this["ReadDoorIsOpen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.BYTE0")]
        public string WriteFrontsideDoor {
            get {
                return ((string)(this["WriteFrontsideDoor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB1.BYTE1")]
        public string WriteBacksideDoor {
            get {
                return ((string)(this["WriteBacksideDoor"]));
            }
        }
    }
}
